Replace DOARR_{EX,IM}PORT macros with doarr::{ex,im}ported types

diff --git a/preproc.template b/preproc.template
--- a/preproc.template
+++ b/preproc.template
@@ -92,15 +92,15 @@ static struct guest_file file = {
 } // namespace
 ' | tr '\t' ' '
 
-$compiler -x c++-header "$source_file" -E -P -DDOARR_EXPORT=__DOARR_EXPORT__ $implicit_flags "$@" > "$tmp" || exit 1
-tr '\n' ' ' < "$tmp" | grep -Eo '__DOARR_EXPORT__(  *[A-Z_a-z][0-9A-Z_a-z]* *\()?' | tr -d '(' | {
+$compiler -x c++-header "$source_file" -E -P $implicit_flags "$@" > "$tmp" || exit 1
+tr '\n' ' ' < "$tmp" | grep -Eo 'doarr::exported(  *[A-Z_a-z][0-9A-Z_a-z]* *\()?' | tr -d '(' | {
 	some=false
 	while read a b
 	do some=true
 		case "$b" in
 		(''|decltype)
-			echo 'Error: DOARR_EXPORT must immediately precede the function name' >&2
-			echo 'Example: void DOARR_EXPORT foo(void *data) { ... }' >&2
+			echo 'Error: doarr::exported must immediately precede the function name' >&2
+			echo 'Example: doarr::exported foo(void *data) { ... }' >&2
 			exit 1
 			;;
 		(*)
